Configured Login Page to handle the case where the user's status in to "ForceChangePassword" in AWS Cognito"
AccordLMS/NogginGuru.CognitoDNN pull request #8
Opened 2024-03-22 12:26 UTC by gouravaccolite

-Added a lable to verify the code sent to email while reseting the user's password.
-Handled the where the user's status in to "ForceChangePassword" in AWS Cognito
-Redirected the user back to login page after succesfull login

2024-03-22 12:34 UTC, jituaccolite approved these changes

2024-03-27 06:33 UTC, vineet-accolitedigital requested changes

2024-03-27 06:33 UTC, vineet-accolitedigital commented on Client/Login.ascx.cs
> +                divEmail.Visible = false;
Remove the same statements out of the if/else block

2024-03-27 07:17 UTC, vineet-accolitedigital approved these changes

2024-03-27 07:28 UTC, merged